version: "3.8"

services:
  database:
    image: postgres
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./api
    # volumes:
    #   - ./api:/app
    #   - /app/node_modules
    env_file:
      - .env
    depends_on:
      - database

  client:
    build: ./client
    # volumes:
    #   - ./client:/app
    #   - /app/node_modules
    depends_on:
      - api

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "3000:80"
    depends_on:
      - client

volumes:
  db_data:
