version: "3.8"
services:
  api:
    build: ./api
    # volumes:
    #   - ./api:/app
    #   - /app/node_modules
    env_file:
      - .env

  client:
    build: ./client
    # volumes:
    #   - ./client:/app
    #   - /app/node_modules
    depends_on:
      - api

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "3000:80"
    depends_on:
      - api
      - client
