version: "3.8"
services:
  database:
    image: postgres
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build: ./server
    ports:
      - "80:80"
    #volumes:
    #  - ./server:/app
    #  - /app/node_modules
    env_file:
      - .env
    depends_on:
      - database
  client:
    build: ./client
    ports:
      - "3000:3000"
    #volumes:
    #  - ./client:/app
    #  - /app/node_modules
    depends_on:
      - server

volumes:
  data:
